spring:
  application:
    name: products
  datasource:
    password: postgres
    username: postgres
    url: ${DB_URL:jdbc:postgresql://localhost:25432/products}
  jpa:
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
xsd:
  tns: http://www.soapws.com/products

server:
  port: 8000

